### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by emlcpfx** [prafull7/materialistic#3]
Trying this in WSL, Ubuntu 22.04, Windows 11, RTX 3090.

![Screenshot 2023-08-07 113146](https://github.com/prafull7/materialistic/assets/91585528/04cf4dcb-2426-4ac7-9475-66b2fa76219a)

**Comment by prafull7** [comment]
Sorry for the inconvenience. Can you delete all the files with the Zone.Identifier in the checkpoint folder. This error is because it is not loading the model.ckpt but instead trying to read from model.ckpt:Zone.Identifier.

**Comment by emlcpfx** [comment]
Thanks! That got me to this next error message:

`(materialistic) eric22@CPFX02:~/materialistic$ python test.py --exp_name materialistic_checkpoint --method_name materialistic_checkpoint --config ./configs/transformer.cfg --data_dir ./data/materialistic_real_data/
Using device:  NVIDIA GeForce RTX 3090
Creating model:  transformer
Making pytorch lightning model
Using cache found in /home/eric22/.cache/torch/hub/facebookresearch_dino_main
['model.ckpt', 'args.pkl']
map_location cuda:0
model.ckpt
dict_keys(['epoch', 'global_step', 'pytorch-lightning_version', 'state_dict', 'loops', 'callbacks', 'optimizer_states', 'lr_schedulers'])
/home/eric22/mambaforge/envs/materialistic/lib/python3.9/site-packages/torchvision/transforms/transforms.py:332: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  warnings.warn(
Traceback (most recent call last):
  File "/home/eric22/materialistic/test.py", line 87, in <module>
    scores, path1, path2, path3, path4, context_embeddings_1, context_embeddings_2, context_embeddings_3, context_embeddings_4, layer_1, layer_2, layer_3, layer_4 = net.net(input, reference_locations)
  File "/home/eric22/mambaforge/envs/materialistic/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/eric22/materialistic/src/models/transformer.py", line 409, in forward
    x = self.dino_model(x)
  File "/home/eric22/mambaforge/envs/materialistic/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/eric22/.cache/torch/hub/facebookresearch_dino_main/vision_transformer.py", line 212, in forward
    x = blk(x)
  File "/home/eric22/mambaforge/envs/materialistic/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/eric22/.cache/torch/hub/facebookresearch_dino_main/vision_transformer.py", line 108, in forward
    y, attn = self.attn(self.norm1(x))
  File "/home/eric22/mambaforge/envs/materialistic/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/eric22/.cache/torch/hub/facebookresearch_dino_main/vision_transformer.py", line 82, in forward
    qkv = self.qkv(x).reshape(B, N, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
  File "/home/eric22/mambaforge/envs/materialistic/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/eric22/mambaforge/envs/materialistic/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)``
